# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from paychex_python_sdk import Paychex

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        paychex = Paychex(
        )
        self.assertIsNotNone(paychex)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
