# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from paychex_python_sdk.paths.companies_company_id_workers.post import AddInProgressWorkersRaw
from paychex_python_sdk.paths.companies_company_id_jobs.post import AddJobRaw
from paychex_python_sdk.paths.companies_company_id_customfields.post import CreateCustomFieldAtCompanyLevelRaw
from paychex_python_sdk.paths.companies_company_id_customfieldscategories.post import CreateCustomFieldCategoryRaw
from paychex_python_sdk.paths.companies_company_id_customfields_customfieldid.delete import DeleteCustomFieldRaw
from paychex_python_sdk.paths.companies_company_id_customfieldscategories_categoryid.delete import DeleteCustomFieldsCategoryRaw
from paychex_python_sdk.paths.companies_company_id_calculationbases.get import GetCalculationBasesRaw
from paychex_python_sdk.paths.companies_company_id_contacttypes.get import GetContactTypesRaw
from paychex_python_sdk.paths.companies_company_id_customfields_custom_field_id.get import GetCustomFieldRaw
from paychex_python_sdk.paths.companies_company_id_customfieldscategories.get import GetCustomFieldCategoriesRaw
from paychex_python_sdk.paths.companies_company_id_customfields.get import GetCustomFieldsRaw
from paychex_python_sdk.paths.companies_company_id_customfieldscategories_category_id.get import GetCustomFieldsCategoryRaw
from paychex_python_sdk.paths.companies_company_id.get import GetInformationRaw
from paychex_python_sdk.paths.companies_company_id_jobs_job_id.get import GetJobInformationRaw
from paychex_python_sdk.paths.companies_company_id_jobsegments.get import GetJobSegmentStructureSetupRaw
from paychex_python_sdk.paths.companies_company_id_jobtitles_job_title_id.get import GetJobTitleRaw
from paychex_python_sdk.paths.companies_company_id_jobs.get import GetJobsRaw
from paychex_python_sdk.paths.companies_company_id_laborassignments_labor_assignment_id.get import GetLaborAssignmentRaw
from paychex_python_sdk.paths.companies_company_id_locations_location_id.get import GetLocationRaw
from paychex_python_sdk.paths.companies_company_id_locations.get import GetLocationsRaw
from paychex_python_sdk.paths.companies_company_id_organizations_org_id.get import GetOrganizationRaw
from paychex_python_sdk.paths.companies_company_id_organizations.get import GetOrganizationsRaw
from paychex_python_sdk.paths.companies_company_id_payfrequencies.get import GetPayFrequenciesRaw
from paychex_python_sdk.paths.companies_company_id_workerstatuses_status_id.get import GetStatusRaw
from paychex_python_sdk.paths.companies_company_id_workers.get import GetWorkersRaw
from paychex_python_sdk.paths.companies.get import ListRaw
from paychex_python_sdk.paths.companies_company_id_jobtitles.get import ListJobTitlesRaw
from paychex_python_sdk.paths.companies_company_id_laborassignments.get import ListLaborAssignmentsRaw
from paychex_python_sdk.paths.companies_company_id_workerstatuses.get import ListWorkerStatusesRaw
from paychex_python_sdk.paths.companies_company_id_customfields_customfieldid.patch import UpdateCustomFieldRaw
from paychex_python_sdk.paths.companies_company_id_customfieldscategories_categoryid.patch import UpdateCustomFieldsCategoryRaw
from paychex_python_sdk.paths.companies_company_id_jobs_job_id.patch import UpdateJobRaw


class CompanyApiRaw(
    AddInProgressWorkersRaw,
    AddJobRaw,
    CreateCustomFieldAtCompanyLevelRaw,
    CreateCustomFieldCategoryRaw,
    DeleteCustomFieldRaw,
    DeleteCustomFieldsCategoryRaw,
    GetCalculationBasesRaw,
    GetContactTypesRaw,
    GetCustomFieldRaw,
    GetCustomFieldCategoriesRaw,
    GetCustomFieldsRaw,
    GetCustomFieldsCategoryRaw,
    GetInformationRaw,
    GetJobInformationRaw,
    GetJobSegmentStructureSetupRaw,
    GetJobTitleRaw,
    GetJobsRaw,
    GetLaborAssignmentRaw,
    GetLocationRaw,
    GetLocationsRaw,
    GetOrganizationRaw,
    GetOrganizationsRaw,
    GetPayFrequenciesRaw,
    GetStatusRaw,
    GetWorkersRaw,
    ListRaw,
    ListJobTitlesRaw,
    ListLaborAssignmentsRaw,
    ListWorkerStatusesRaw,
    UpdateCustomFieldRaw,
    UpdateCustomFieldsCategoryRaw,
    UpdateJobRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
