# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from paychex_python_sdk.paths.workers_worker_id_communications.post import AddCommunicationRaw
from paychex_python_sdk.paths.workers_worker_id_directdeposits.post import AddDirectDepositRaw
from paychex_python_sdk.paths.workers_worker_id_federaltax.post import AddFederalTaxSetupRaw
from paychex_python_sdk.paths.workers_worker_id_paycomponents.post import AddPayComponentRaw
from paychex_python_sdk.paths.workers_worker_id_compensation_payrates.post import AddPayRateRaw
from paychex_python_sdk.paths.workers_worker_id_contacts.post import AddWorkerContactsRaw
from paychex_python_sdk.paths.workers_worker_id_customfields.post import CreateCustomFieldRaw
from paychex_python_sdk.paths.workers_worker_id_contacts_contact_id.delete import DeleteContactByContactIdRaw
from paychex_python_sdk.paths.workers_worker_id_customfields_worker_custom_field_id.delete import DeleteCustomFieldRaw
from paychex_python_sdk.paths.workers_worker_id.delete import DeleteInProgressRaw
from paychex_python_sdk.paths.workers_worker_id_communications_communication_id.get import GetCommunicationItemRaw
from paychex_python_sdk.paths.workers_worker_id_communications.get import GetCommunicationsRaw
from paychex_python_sdk.paths.workers_worker_id_compensation.get import GetCompensationInformationRaw
from paychex_python_sdk.paths.workers_worker_id_contacts_contact_id.get import GetContactByContactIdRaw
from paychex_python_sdk.paths.workers_worker_id_contacts.get import GetContactsRaw
from paychex_python_sdk.paths.workers_worker_id_customfields_worker_custom_field_id.get import GetCustomFieldRaw
from paychex_python_sdk.paths.workers_worker_id_customfields.get import GetCustomFieldsRaw
from paychex_python_sdk.paths.workers_worker_id_directdeposits_direct_deposit_id.get import GetDirectDepositRaw
from paychex_python_sdk.paths.workers_worker_id_federaltax.get import GetFederalTaxSetupRaw
from paychex_python_sdk.paths.workers_worker_id.get import GetInformationRaw
from paychex_python_sdk.paths.workers_worker_id_paycomponents_worker_component_id.get import GetPayComponentRaw
from paychex_python_sdk.paths.workers_worker_id_paycomponents.get import GetPayComponentsRaw
from paychex_python_sdk.paths.workers_worker_id_compensation_payrates_rate_id.get import GetPayRateRaw
from paychex_python_sdk.paths.workers_worker_id_compensation_payrates.get import GetPayRatesByWorkerIdRaw
from paychex_python_sdk.paths.workers_worker_id_compensation_paystandards.get import GetPayStandardsRaw
from paychex_python_sdk.paths.workers_worker_id_timeoff.get import GetTimeOffBalanceRaw
from paychex_python_sdk.paths.workers_worker_id_status.get import GetWorkerStatusListRaw
from paychex_python_sdk.paths.workers_worker_id_assignmentdistributions.get import ListAssignmentDistributionsRaw
from paychex_python_sdk.paths.workers_worker_id_directdeposits.get import ListDirectDepositsRaw
from paychex_python_sdk.paths.workers_worker_id_communications_communication_id.delete import RemoveCommunicationRaw
from paychex_python_sdk.paths.workers_worker_id_directdeposits_direct_deposit_id.delete import RemoveDirectDepositRaw
from paychex_python_sdk.paths.workers_worker_id_federaltax.delete import RemoveFederalTaxRaw
from paychex_python_sdk.paths.workers_worker_id_paycomponents_worker_component_id.delete import RemovePayComponentRaw
from paychex_python_sdk.paths.workers_worker_id_compensation_payrates_rate_id.delete import RemovePayRateRaw
from paychex_python_sdk.paths.workers_worker_id_communications_communication_id.patch import UpdateCommunicationItemRaw
from paychex_python_sdk.paths.workers_worker_id_compensation_payrates_rate_id.patch import UpdateCompensationRateRaw
from paychex_python_sdk.paths.workers_worker_id_contacts_contact_id.patch import UpdateContactRaw
from paychex_python_sdk.paths.workers_worker_id_customfields_worker_custom_field_id.patch import UpdateCustomFieldRaw
from paychex_python_sdk.paths.workers_worker_id_directdeposits_direct_deposit_id.patch import UpdateDirectDepositRaw
from paychex_python_sdk.paths.workers_worker_id_directdeposits.patch import UpdateDirectDepositsRaw
from paychex_python_sdk.paths.workers_worker_id_federaltax.patch import UpdateFederalTaxSetupRaw
from paychex_python_sdk.paths.workers_worker_id_paycomponents_worker_component_id.patch import UpdatePayComponentRaw
from paychex_python_sdk.paths.workers_worker_id_paycomponents.patch import UpdatePayComponentsRaw
from paychex_python_sdk.paths.workers_worker_id.patch import UpdateUniqueWorkerRaw


class WorkerApiRaw(
    AddCommunicationRaw,
    AddDirectDepositRaw,
    AddFederalTaxSetupRaw,
    AddPayComponentRaw,
    AddPayRateRaw,
    AddWorkerContactsRaw,
    CreateCustomFieldRaw,
    DeleteContactByContactIdRaw,
    DeleteCustomFieldRaw,
    DeleteInProgressRaw,
    GetCommunicationItemRaw,
    GetCommunicationsRaw,
    GetCompensationInformationRaw,
    GetContactByContactIdRaw,
    GetContactsRaw,
    GetCustomFieldRaw,
    GetCustomFieldsRaw,
    GetDirectDepositRaw,
    GetFederalTaxSetupRaw,
    GetInformationRaw,
    GetPayComponentRaw,
    GetPayComponentsRaw,
    GetPayRateRaw,
    GetPayRatesByWorkerIdRaw,
    GetPayStandardsRaw,
    GetTimeOffBalanceRaw,
    GetWorkerStatusListRaw,
    ListAssignmentDistributionsRaw,
    ListDirectDepositsRaw,
    RemoveCommunicationRaw,
    RemoveDirectDepositRaw,
    RemoveFederalTaxRaw,
    RemovePayComponentRaw,
    RemovePayRateRaw,
    UpdateCommunicationItemRaw,
    UpdateCompensationRateRaw,
    UpdateContactRaw,
    UpdateCustomFieldRaw,
    UpdateDirectDepositRaw,
    UpdateDirectDepositsRaw,
    UpdateFederalTaxSetupRaw,
    UpdatePayComponentRaw,
    UpdatePayComponentsRaw,
    UpdateUniqueWorkerRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
