# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAuthentication1(TypedDict):
    # The authorization method used to authorize callers to your webhook url.
    authType: str

class OptionalAuthentication1(TypedDict, total=False):
    # The API key required for API_KEY authorization.
    apiKey: str

    # The username required for BASIC_AUTH authorization.
    username: str

    # The password required for BASIC_AUTH authorization.
    password: str

    # The URL used to obtain an access token for OAUTH2 or OAUTH2_BASIC authorization.
    tokenUrl: str

    # The client ID required by OAUTH2 and OAUTH2_BASIC authorization.
    clientId: str

    # The client secret required by OAUTH2 and OAUTH2_BASIC authorization.
    clientSecret: str

    # The grant type used to acquire an access token by OAUTH2 and OAUTH2_BASIC authorization.
    grantType: str

    # The content type to use in the token request for OAUTH2 and OAUTH2_BASIC authorization.
    contentType: str

class Authentication1(RequiredAuthentication1, OptionalAuthentication1):
    pass
