# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.link import Link

class RequiredCheckSummaryResource(TypedDict):
    pass

class OptionalCheckSummaryResource(TypedDict, total=False):
    payPeriodId: str

    checkDate: datetime

    payRunDate: datetime

    totalHrs: str

    checkNumber: str

    totalEarnings: str

    totalWithholdings: str

    totalDeductions: str

    netPay: str

    checkType: str

    grossYTD: str

    netYTD: str

    links: typing.List[Link]

class CheckSummaryResource(RequiredCheckSummaryResource, OptionalCheckSummaryResource):
    pass
