# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.client_account_relation import ClientAccountRelation
from paychex_python_sdk.type.client_address import ClientAddress
from paychex_python_sdk.type.client_name import ClientName
from paychex_python_sdk.type.client_version import ClientVersion

class RequiredClient(TypedDict):
    pass

class OptionalClient(TypedDict, total=False):
    lockVersion: int

    createdByApplicationName: str

    createdByUserId: str

    createdDate: datetime

    createdByApplicationSubProcessName: str

    clientAccountRelations: 'typing.List[ClientAccountRelation]'

    clientAddresses: 'typing.List[ClientAddress]'

    clientNames: 'typing.List[ClientName]'

    clientVersions: 'typing.List[ClientVersion]'

    ceid: str

class Client(RequiredClient, OptionalClient):
    pass
