# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredClientPayComponentOptions(TypedDict):
    pass

class OptionalClientPayComponentOptions(TypedDict, total=False):
    optValueId: int

    optValueName: str

    optValueTypeId: int

    optValue: str

class ClientPayComponentOptions(RequiredClientPayComponentOptions, OptionalClientPayComponentOptions):
    pass
