# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

if TYPE_CHECKING:
    from paychex_python_sdk.type.client import Client
if TYPE_CHECKING:
    from paychex_python_sdk.type.client_name_version import ClientNameVersion

class RequiredClientName(TypedDict):
    pass

class OptionalClientName(TypedDict, total=False):
    id: int

    type: str

    createdDate: datetime

    createdByApplicationName: str

    createdByUserId: str

    createdByApplicationSubProcessName: str

    clients: 'Client'

    clientNameVersions: 'typing.List[ClientNameVersion]'

class ClientName(RequiredClientName, OptionalClientName):
    pass
