# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

if TYPE_CHECKING:
    from paychex_python_sdk.type.client_name import ClientName

class RequiredClientNameVersion(TypedDict):
    pass

class OptionalClientNameVersion(TypedDict, total=False):
    cnvId: int

    cnvCltNm: str

    cnvVerStatCd: str

    cnvValStatCd: str

    cnvBegnEffDt: datetime

    cnvEndEffDt: datetime

    cnvModDt: datetime

    cnvModByAppNm: str

    cnvModByAppUsrNm: str

    cnvModByAppSubNm: str

    cltNmByCnId: 'ClientName'

class ClientNameVersion(RequiredClientNameVersion, OptionalClientNameVersion):
    pass
