# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.collection_resource_content import CollectionResourceContent
from paychex_python_sdk.type.error_resource import ErrorResource
from paychex_python_sdk.type.link import Link
from paychex_python_sdk.type.metadata_resource import MetadataResource

class RequiredCollectionResource(TypedDict):
    pass

class OptionalCollectionResource(TypedDict, total=False):
    metadata: MetadataResource

    content: CollectionResourceContent

    errors: typing.List[ErrorResource]

    message: str

    links: typing.List[Link]

class CollectionResource(RequiredCollectionResource, OptionalCollectionResource):
    pass
