# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCommunicationResource(TypedDict):
    pass

class OptionalCommunicationResource(TypedDict, total=False):
    # The unique ID associated with communication 
    communicationId: str

    # A set of communication types classifying an instruction that the customer, requester, or subject must comply with in order for the screening to go forward. NOTE: PHONE and EMAIL type supports BUSINESS and PERSONAL usage type only.MOBILE_PHONE, FAX and PAGER supports BUSINESS usage type only.This data field cannot be PATCHED.
    type: str

    # A code classifying a designated use associated with a contact method. For example, whether a telephone or email address is one for business communications or one primarily for personal use.This data field cannot be PATCHED.
    usageType: str

    # The country dialing code for a communication number.
    dialCountry: str

    # The area dialing code for a communication number.
    dialArea: str

    # The communication number, not including country dialing or area dialing codes.
    dialNumber: str

    # The extension of the associated communication number.
    dialExtension: str

    # The mailto address as specified in RFC2368 .
    uri: str

    # The street address line one
    streetLineOne: str

    # The street address line two
    streetLineTwo: str

    # The postal office box. This data field cannot be PATCHED.
    postOfficeBox: str

    # The city name
    city: str

    # The zip-code
    postalCode: str

    # The zip-code extension
    postalCodeExtension: str

    # The state code (ISO 3166 subdivision code). This data field cannot be PATCHED for ACTIVE worker.
    countrySubdivisionCode: str

    # The country code (ISO 3166 alpha-2)
    countryCode: str

class CommunicationResource(RequiredCommunicationResource, OptionalCommunicationResource):
    pass
