# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.communication_resource import CommunicationResource
from paychex_python_sdk.type.legal_id_resource import LegalIdResource
from paychex_python_sdk.type.link import Link

class RequiredCompanyResource(TypedDict):
    pass

class OptionalCompanyResource(TypedDict, total=False):
    # The unique identifier associated with this companies representation.
    companyId: str

    # The client account number used for identification purposes. (no dash or spaces allowed, only the last 8 characters  of the ID)
    displayId: str

    # The legal name of the company.
    legalName: str

    legalId: LegalIdResource

    communications: typing.List[CommunicationResource]

    links: typing.List[Link]

class CompanyResource(RequiredCompanyResource, OptionalCompanyResource):
    pass
