# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.custom_fields_dropdown_resource import CustomFieldsDropdownResource
from paychex_python_sdk.type.link import Link

class RequiredCustomFieldsResource(TypedDict):
    pass

class OptionalCustomFieldsResource(TypedDict, total=False):
    # The unique identifier that is autogenerated when a custom field is created
    customFieldId: str

    # The name of the custom field
    customFieldName: str

    # The unique identifier that is autogenerated when creating a category
    categoryId: str

    # Where to indicate if the custom field is required on the worker where true = required and false = not required
    required: bool

    # Where to indicate if the custom field is required on the worker's pay stub, where true = required and false = not required
    checkStub: bool

    # Where to indicate if the custom field is able to be edited by the employee, where true = required and false = not required
    employeeEditable: bool

    # The type of field the custom field is.
    type: str

    # The value for BOOLEAN type (true / false)
    booleanValue: bool

    links: typing.List[Link]

    # The value for DATE type , example : 2012-02-01T05:00:00Z
    dateValue: datetime

    # The value for TEXT type (any text, alphanumeric, special characters allowed)
    textValue: str

    # The maximum allowed value for textValue
    maxTextLength: typing.Union[int, float]

    # Numeric data type can have three formats namely - whole number, second decimal place and fourth decimal place, example: 12 , 12.34 or 12.3456
    numericValue: typing.Union[int, float]

    dropdown: typing.List[CustomFieldsDropdownResource]

class CustomFieldsResource(RequiredCustomFieldsResource, OptionalCustomFieldsResource):
    pass
