# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDeepUrlResponseResource(TypedDict):
    pass

class OptionalDeepUrlResponseResource(TypedDict, total=False):
    # The deeplink URL that redirects a Flex client Admin to the Flex integrated apps drawer for their approval or denial of the partner integration
    approvalLink: str

class DeepUrlResponseResource(RequiredDeepUrlResponseResource, OptionalDeepUrlResponseResource):
    pass
