# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.link import Link

class RequiredDirectDepositResource(TypedDict):
    pass

class OptionalDirectDepositResource(TypedDict, total=False):
    # The ID for the direct deposit item.
    directDepositId: str

    # The date that this direct deposit will be applied to future pay periods. This data field cannot be PATCHED.
    startDate: datetime

    # A type of payment for the direct deposit.
    paymentType: str

    # Financial institutions account type. This data field cannot be PATCHED.
    accountType: str

    # The amount to be applied to this direct deposit.
    value: typing.Union[int, float]

    # The financial institutions routing number.This data field cannot be PATCHED.
    routingNumber: str

    # The financial institutions account number.This data field cannot be PATCHED.
    accountNumber: str

    # The priority order for which the direct deposits will be performed in. When a new direct deposit is added the priority will be assigned. The priority can be modified only by swapping with a different direct deposit using the bulk PATCH. A paymentType of REMAINDER will show a priority of 99 and can't be modified.This data field cannot be PATCHED.
    priority: str

    links: typing.List[Link]

class DirectDepositResource(RequiredDirectDepositResource, OptionalDirectDepositResource):
    pass
