# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.email_resource import EmailResource
from paychex_python_sdk.type.postal_resource import PostalResource
from paychex_python_sdk.type.telecom_resource import TelecomResource

class RequiredEntityCommunicationResource(TypedDict):
    pass

class OptionalEntityCommunicationResource(TypedDict, total=False):
    telecom: TelecomResource

    postal: PostalResource

    email: EmailResource

class EntityCommunicationResource(RequiredEntityCommunicationResource, OptionalEntityCommunicationResource):
    pass
