# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.link import Link
from paychex_python_sdk.type.pay_component_frequency_type_resource import PayComponentFrequencyTypeResource

class RequiredFrequencyCombinationUnitResource(TypedDict):
    pass

class OptionalFrequencyCombinationUnitResource(TypedDict, total=False):
    # Frequency which the pay component would be applied.
    payFrequency: str

    payComponentFrequency: PayComponentFrequencyTypeResource

    links: typing.List[Link]

class FrequencyCombinationUnitResource(RequiredFrequencyCombinationUnitResource, OptionalFrequencyCombinationUnitResource):
    pass
