# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredJobSegmentsResource(TypedDict):
    pass

class OptionalJobSegmentsResource(TypedDict, total=False):
    # This is segment 1 or the number associated to the job when segmentation is not used.
    segment1: str

    # This is segment 2.
    segment2: str

    # This is segment 3.
    segment3: str

class JobSegmentsResource(RequiredJobSegmentsResource, OptionalJobSegmentsResource):
    pass
