# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.link import Link

class RequiredLaborAssignmentResource(TypedDict):
    pass

class OptionalLaborAssignmentResource(TypedDict, total=False):
    # The unique identifier associated with this labor assignment representation.
    laborAssignmentId: str

    # The name of the labor assignment.
    name: str

    # The start date associated with this labor assignment.
    startDate: datetime

    # The end date associated with this labor assignment.
    endDate: datetime

    # The organization associated with this labor assignment.
    organizationId: str

    # The position associated with this labor assignment.
    positionId: str

    links: typing.List[Link]

    # The locations associated with this labor assignment.
    locationId: str

class LaborAssignmentResource(RequiredLaborAssignmentResource, OptionalLaborAssignmentResource):
    pass
