# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredNameResource(TypedDict):
    pass

class OptionalNameResource(TypedDict, total=False):
    # The family or last name of a worker.
    familyName: str

    # A subordinate given name, or initial representing that name, of a worker. <br />NOTE:  More than one char is not allowed and returns an error. <br />A full middle name can be added directly via Paychex Flex only at this time.
    middleName: str

    # The given or first name of a worker. For an independent contractor that is a company rather than an individual, the name of the company.
    givenName: str

    # The name that the worker prefers to go by; also known as a \"nickname\"
    preferredName: str

    # A qualifier to the name of a worker, indicating generation.
    qualificationAffixCode: str

    # A personal title that comes before an individual's name in a formal address (such as Dr., Prof., Rev., Mr.). 
    titleAffixCode: str

class NameResource(RequiredNameResource, OptionalNameResource):
    pass
