# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayStandardResource(TypedDict):
    pass

class OptionalPayStandardResource(TypedDict, total=False):
    # How often a worker is paid.
    payFrequency: str

    # Default overtime factor that would be applied for overtime work completed.
    overtimeFactor: str

    # Calculated amount of compensation based on rate defaults.
    calculatedPayPeriod: str

    # Calculated amount of compensation based on calculatedPayPeriod and payFrequency.
    calculatedAnnualSalary: str

class PayStandardResource(RequiredPayStandardResource, OptionalPayStandardResource):
    pass
