# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.link import Link

class RequiredPayRateResource(TypedDict):
    pass

class OptionalPayRateResource(TypedDict, total=False):
    # Describes the rate for the worker.
    description: str

    # Unique identifier for this workers pay rate. **This ID will change if this is created for an IN_PROGRESS worker that is later completed within Flex**
    rateId: str

    # The date when the pay rate is going to begin.
    startDate: datetime

    # The number of the rate. A worker can have up to 5 different rates.
    rateNumber: str

    # Type of rate.
    rateType: str

    # The currency amount which this rate is applied.
    amount: str

    # Default standard hours that this rate is used with a pay frequency.
    standardHours: str

    # Default over time hours that this rate is used with a pay frequency.
    standardOvertime: str

    # If this rate is the default one to apply on the worker.
    default: bool

    # The date when the pay rate becomes effective for the worker.(can be used only in POST/PATCH for an active worker)
    effectiveDate: str

    links: typing.List[Link]

class PayRateResource(RequiredPayRateResource, OptionalPayRateResource):
    pass
