# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayComponent(TypedDict):
    pass

class OptionalPayComponent(TypedDict, total=False):
    cltpcId: int

    offeringId: str

    pcId: int

    customName: str

    reportCode: str

    isPaychexAdministered: bool

    deductionPriority: int

    refId: int

    payCompName: str

    payCpntTypeId: int

    payCpntType: str

    classTypeId: int

    classType: str

    payFreqId: int

    payFreq: str

    freqTypeId: int

    freqType: str

    firstCheckRuleId: int

    firstCheckRule: str

    isBankRequired: bool

    collectArrearsOnShortfall: bool

    startDate: datetime

    endDate: datetime

class PayComponent(RequiredPayComponent, OptionalPayComponent):
    pass
