# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.organization_resource2 import OrganizationResource2

class RequiredProcessedCheckComponentResource(TypedDict):
    pass

class OptionalProcessedCheckComponentResource(TypedDict, total=False):
    componentId: str

    checkComponentId: str

    name: str

    classificationType: str

    effectOnPay: str

    memoed: bool

    laborAssignmentId: str

    organization: OrganizationResource2

    jobName: str

    jobId: str

    paidBy: str

    lineDate: datetime

    amount: str

    rate: str

    hours: str

    units: str

class ProcessedCheckComponentResource(RequiredProcessedCheckComponentResource, OptionalProcessedCheckComponentResource):
    pass
