# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.entity_resource import EntityResource
from paychex_python_sdk.type.person_resource import PersonResource
from paychex_python_sdk.type.relation_type_resource1 import RelationTypeResource1

class RequiredRelationshipResource(TypedDict):
    pass

class OptionalRelationshipResource(TypedDict, total=False):
    # The ID for the workers relationship to contact.
    relationshipId: str

    # The ID for the workers specific relation.
    relationWeid: str

    relationshipType: RelationTypeResource1

    # Where to indicate if the contact is selected as Primary, where true = Primary contact and false = not Primary contact.
    primary: bool

    person: PersonResource

    entity: EntityResource

class RelationshipResource(RequiredRelationshipResource, OptionalRelationshipResource):
    pass
