# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredStatus(TypedDict):
    pass

class OptionalStatus(TypedDict, total=False):
    # The unique identifier associated with this status representation.
    workerStatusId: str

    # The workers current status.
    statusType: str

    # The detailed reason of the workers current status.
    statusReason: str

class Status(RequiredStatus, OptionalStatus):
    pass
