# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.name_resource1 import NameResource1

class RequiredSupervisorResource1(TypedDict):
    pass

class OptionalSupervisorResource1(TypedDict, total=False):
    # The supervisor's Id
    workerId: str

    name: NameResource1

class SupervisorResource1(RequiredSupervisorResource1, OptionalSupervisorResource1):
    pass
