# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTelecomResource(TypedDict):
    pass

class OptionalTelecomResource(TypedDict, total=False):
    # The ID for the workers relationship to contact.
    communicationId: str

    # The country code. Required for POST contacts.
    dialCountry: str

    # The area code. Required for POST contacts.
    dialArea: str

    # The phone number. Required for POST contacts.
    dialNumber: str

    # Enum: \"PHONE\", \"MOBILE_PHONE\"  Indicates whether or not the number is for a mobile device. Required for POST contacts.
    type: str

    # Enum: \"PERSONAL\", \"BUSINESS\"  A code classifying a designated use associated with a contact method. For example, whether a telephone or email address is one for work communications or one primarily for personal use. This data field cannot be PATCHED. Required for POST contacts.
    usageType: str

    # The phone extension.
    extension: str

class TelecomResource(RequiredTelecomResource, OptionalTelecomResource):
    pass
