# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.webhooks_get_specific_hook_by_id_response_domains import WebhooksGetSpecificHookByIdResponseDomains

class RequiredWebhooksGetSpecificHookByIdResponse(TypedDict):
    pass

class OptionalWebhooksGetSpecificHookByIdResponse(TypedDict, total=False):
    hookId: str

    companyId: str

    uri: str

    authType: str

    createdDate: str

    domains: WebhooksGetSpecificHookByIdResponseDomains

class WebhooksGetSpecificHookByIdResponse(RequiredWebhooksGetSpecificHookByIdResponse, OptionalWebhooksGetSpecificHookByIdResponse):
    pass
