# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.authentication1 import Authentication1
from paychex_python_sdk.type.link import Link
from paychex_python_sdk.type.webhook_request_domains import WebhookRequestDomains

class RequiredWebhookRequest(TypedDict):
    # Enter a valid URL for the webhook to receive events.
    uri: str

    authentication: Authentication1

    domains: WebhookRequestDomains

class OptionalWebhookRequest(TypedDict, total=False):
    # The unique identifier associated with this webhook. Not required for Posting.
    hookId: str

    # ID associated with desired company that will receive the webhook notifications. NOTE: If no Company ID is provided in the POST, then all companies linked to the app will receive notifications.
    companyId: str

    links: typing.List[Link]

class WebhookRequest(RequiredWebhookRequest, OptionalWebhookRequest):
    pass
