# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.webhooks_list_response_item_domains import WebhooksListResponseItemDomains

class RequiredWebhooksListResponseItem(TypedDict):
    pass

class OptionalWebhooksListResponseItem(TypedDict, total=False):
    hookId: str

    companyId: str

    uri: str

    authType: str

    createdDate: str

    domains: WebhooksListResponseItemDomains

class WebhooksListResponseItem(RequiredWebhooksListResponseItem, OptionalWebhooksListResponseItem):
    pass
