# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.communication_resource import CommunicationResource
from paychex_python_sdk.type.job_title_resource import JobTitleResource
from paychex_python_sdk.type.legal_id_resource import LegalIdResource
from paychex_python_sdk.type.name_resource import NameResource
from paychex_python_sdk.type.organization_resource import OrganizationResource
from paychex_python_sdk.type.status import Status
from paychex_python_sdk.type.supervisor_resource import SupervisorResource

class RequiredWorkerResource(TypedDict):
    pass

class OptionalWorkerResource(TypedDict, total=False):
    # The unique identifier associated with this worker representation.
    workerId: str

    # The workers employee identification information.
    employeeId: str

    # The type of worker. This data field cannot be PATCHED.
    workerType: str

    # The type of employment for the worker.
    employmentType: str

    # The Overtime classification of the worker.This data field cannot be PATCHED for ACTIVE workers.
    exemptionType: str

    # The workers date of birth. It cannot be greater than today's date.
    birthDate: datetime

    sex: str

    # Disclaimer:This parameter is not visible in Flex for the client. This data field cannot be PATCHED for ACTIVE workers.
    ethnicityCode: str

    # The date which the worker was hired. It cannot be PATCHED for ACTIVE workers.
    hireDate: datetime

    # The clock ID of the worker that can be an identification for other systems.
    clockId: str

    name: NameResource

    legalId: LegalIdResource

    # The workers home labor assignment. This data field cannot be POSTED or PATCHED
    laborAssignmentId: str

    # The workers home job. This data field cannot be POSTED or PATCHED.
    jobId: str

    # The workers location. This data field cannot be POSTED or PATCHED.
    locationId: str

    job: JobTitleResource

    organization: OrganizationResource

    supervisor: SupervisorResource

    currentStatus: Status

    # Worker Communications. This data field cannot be updated for worker endpoint.
    communications: typing.List[CommunicationResource]

    # Id that you define which is used for error handling/responses.This data field is used while POSTING multiple IN_PROGRESS workers
    workerCorrelationId: str

class WorkerResource(RequiredWorkerResource, OptionalWorkerResource):
    pass
