# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from paychex_python_sdk.type.communication_resource1 import CommunicationResource1
from paychex_python_sdk.type.job_title_resource1 import JobTitleResource1
from paychex_python_sdk.type.legal_id_resource1 import LegalIdResource1
from paychex_python_sdk.type.link import Link
from paychex_python_sdk.type.name_resource1 import NameResource1
from paychex_python_sdk.type.organization_resource1 import OrganizationResource1
from paychex_python_sdk.type.status1 import Status1
from paychex_python_sdk.type.supervisor_resource1 import SupervisorResource1

class RequiredWorkerResource1(TypedDict):
    pass

class OptionalWorkerResource1(TypedDict, total=False):
    # The unique identifier associated with this worker representation.
    workerId: str

    # The workers employee identification information.
    employeeId: str

    # The type of worker. This data field cannot be PATCHED.
    workerType: str

    # The type of employment for the worker.
    employmentType: str

    # The Overtime classification of the worker. This data field cannot be PATCHED for ACTIVE workers.
    exemptionType: str

    # The workers date of birth. It cannot be greater than today's date.
    birthDate: datetime

    sex: str

    # Disclaimer:This parameter is not visible in Flex for the client. This data field cannot be PATCHED for ACTIVE workers.
    ethnicityCode: str

    # The date which the worker was hired. It cannot be PATCHED for ACTIVE workers.
    hireDate: datetime

    # The clock ID of the worker that can be an identification for other systems.
    clockId: str

    name: NameResource1

    legalId: LegalIdResource1

    # The workers home labor assignment. This data field cannot be POSTED or PATCHED.
    laborAssignmentId: str

    # The workers location. This data field cannot be POSTED or PATCHED.
    locationId: str

    # The workers home job. This data field cannot be POSTED or PATCHED.
    jobId: str

    job: JobTitleResource1

    organization: OrganizationResource1

    supervisor: SupervisorResource1

    currentStatus: Status1

    # Worker Communications. This data field cannot be updated for worker endpoint.
    communications: typing.List[CommunicationResource1]

    links: typing.List[Link]

    # Id that you define which is used for error handling/responses.This data field is used while POSTING multiple IN_PROGRESS workers
    workerCorrelationId: str

class WorkerResource1(RequiredWorkerResource1, OptionalWorkerResource1):
    pass
