# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import unittest

import paychex_python_sdk
from paychex_python_sdk.model.relation_type_resource1 import RelationTypeResource1
from paychex_python_sdk import configuration


class TestRelationTypeResource1(unittest.TestCase):
    """RelationTypeResource1 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
