# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

if TYPE_CHECKING:
    from paychex_python_sdk.pydantic.client_name import ClientName

class ClientNameVersion(BaseModel):
    cnv_id: typing.Optional[int] = Field(None, alias='cnvId')

    cnv_clt_nm: typing.Optional[str] = Field(None, alias='cnvCltNm')

    cnv_ver_stat_cd: typing.Optional[str] = Field(None, alias='cnvVerStatCd')

    cnv_val_stat_cd: typing.Optional[str] = Field(None, alias='cnvValStatCd')

    cnv_begn_eff_dt: typing.Optional[datetime] = Field(None, alias='cnvBegnEffDt')

    cnv_end_eff_dt: typing.Optional[datetime] = Field(None, alias='cnvEndEffDt')

    cnv_mod_dt: typing.Optional[datetime] = Field(None, alias='cnvModDt')

    cnv_mod_by_app_nm: typing.Optional[str] = Field(None, alias='cnvModByAppNm')

    cnv_mod_by_app_usr_nm: typing.Optional[str] = Field(None, alias='cnvModByAppUsrNm')

    cnv_mod_by_app_sub_nm: typing.Optional[str] = Field(None, alias='cnvModByAppSubNm')

    clt_nm_by_cn_id: typing.Optional['ClientName'] = Field(None, alias='cltNmByCnId')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
