# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

if TYPE_CHECKING:
    from paychex_python_sdk.pydantic.client import Client

class ClientAccountRelation(BaseModel):
    id: typing.Optional[int] = Field(None, alias='id')

    application_name: typing.Optional[str] = Field(None, alias='applicationName')

    assigned_name: typing.Optional[str] = Field(None, alias='assignedName')

    sib_application_name: typing.Optional[str] = Field(None, alias='sibApplicationName')

    sib_assigned_name: typing.Optional[str] = Field(None, alias='sibAssignedName')

    created_date: typing.Optional[datetime] = Field(None, alias='createdDate')

    end_date: typing.Optional[datetime] = Field(None, alias='endDate')

    created_by_application_name: typing.Optional[str] = Field(None, alias='createdByApplicationName')

    created_by_user_id: typing.Optional[str] = Field(None, alias='createdByUserId')

    created_by_application_sub_process_name: typing.Optional[str] = Field(None, alias='createdByApplicationSubProcessName')

    modified_date: typing.Optional[datetime] = Field(None, alias='modifiedDate')

    modified_by_application_name: typing.Optional[str] = Field(None, alias='modifiedByApplicationName')

    modified_by_application_sub_process_name: typing.Optional[str] = Field(None, alias='modifiedByApplicationSubProcessName')

    modified_by_user_id: typing.Optional[str] = Field(None, alias='modifiedByUserId')

    client: typing.Optional['Client'] = Field(None, alias='client')

    caid: typing.Optional[str] = Field(None, alias='caid')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
