# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from paychex_python_sdk.pydantic.link import Link
from paychex_python_sdk.pydantic.relation_type_resource import RelationTypeResource

class ContactTypeResource(BaseModel):
    contact_type_id: typing.Optional[str] = Field(None, alias='contactTypeId')

    contact_type_name: typing.Optional[str] = Field(None, alias='contactTypeName')

    relationship_types: typing.Optional[typing.List[RelationTypeResource]] = Field(None, alias='relationshipTypes')

    links: typing.Optional[typing.List[Link]] = Field(None, alias='links')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
