# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from paychex_python_sdk.pydantic.email_resource import EmailResource
from paychex_python_sdk.pydantic.postal_resource import PostalResource
from paychex_python_sdk.pydantic.telecom_resource import TelecomResource

class EntityCommunicationResource(BaseModel):
    telecom: typing.Optional[TelecomResource] = Field(None, alias='telecom')

    postal: typing.Optional[PostalResource] = Field(None, alias='postal')

    email: typing.Optional[EmailResource] = Field(None, alias='email')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
