# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class HealthMonitoringMBean(BaseModel):
    health: typing.Optional[bool] = Field(None, alias='health')

    health_reason: typing.Optional[str] = Field(None, alias='healthReason')

    busy_reason: typing.Optional[str] = Field(None, alias='busyReason')

    busy: typing.Optional[bool] = Field(None, alias='busy')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
