# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class JobTitleResource1(BaseModel):
    # The name of the title that the worker is assigned to.
    title: typing.Optional[str] = Field(None, alias='title')

    # Unique ID for that job within the company that the worker is assigned to.
    job_title_id: typing.Optional[str] = Field(None, alias='jobTitleId')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
