# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from paychex_python_sdk.pydantic.link import Link

class LaborAssignmentResource(BaseModel):
    # The unique identifier associated with this labor assignment representation.
    labor_assignment_id: typing.Optional[str] = Field(None, alias='laborAssignmentId')

    # The name of the labor assignment.
    name: typing.Optional[str] = Field(None, alias='name')

    # The start date associated with this labor assignment.
    start_date: typing.Optional[datetime] = Field(None, alias='startDate')

    # The end date associated with this labor assignment.
    end_date: typing.Optional[datetime] = Field(None, alias='endDate')

    # The organization associated with this labor assignment.
    organization_id: typing.Optional[str] = Field(None, alias='organizationId')

    # The position associated with this labor assignment.
    position_id: typing.Optional[str] = Field(None, alias='positionId')

    links: typing.Optional[typing.List[Link]] = Field(None, alias='links')

    # The locations associated with this labor assignment.
    location_id: typing.Optional[str] = Field(None, alias='locationId')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
