# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from paychex_python_sdk.pydantic.communication_resource import CommunicationResource
from paychex_python_sdk.pydantic.link import Link

class LocationResource(BaseModel):
    # The unique identifier associated with this locations representation.
    location_id: typing.Optional[str] = Field(None, alias='locationId')

    # The name of the location.
    name: typing.Optional[str] = Field(None, alias='name')

    address: typing.Optional[CommunicationResource] = Field(None, alias='address')

    links: typing.Optional[typing.List[Link]] = Field(None, alias='links')

    # The date which the location was moved into.
    moved_in: typing.Optional[datetime] = Field(None, alias='movedIn')

    # The date which the location was moved out.
    moved_out: typing.Optional[datetime] = Field(None, alias='movedOut')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
