# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from paychex_python_sdk.pydantic.pay_rate_resource import PayRateResource
from paychex_python_sdk.pydantic.pay_standard_resource import PayStandardResource

class PayRatesStandardResource(BaseModel):
    pay_standards: typing.Optional[PayStandardResource] = Field(None, alias='payStandards')

    pay_rates: typing.Optional[typing.List[PayRateResource]] = Field(None, alias='payRates')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
