# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class PayStandardResource(BaseModel):
    # How often a worker is paid.
    pay_frequency: typing.Optional[Literal["WEEKLY", "BI_WEEKLY", "SEMI_MONTHLY", "MONTHLY"]] = Field(None, alias='payFrequency')

    # Default overtime factor that would be applied for overtime work completed.
    overtime_factor: typing.Optional[str] = Field(None, alias='overtimeFactor')

    # Calculated amount of compensation based on rate defaults.
    calculated_pay_period: typing.Optional[str] = Field(None, alias='calculatedPayPeriod')

    # Calculated amount of compensation based on calculatedPayPeriod and payFrequency.
    calculated_annual_salary: typing.Optional[str] = Field(None, alias='calculatedAnnualSalary')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
