# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class Status(BaseModel):
    # The unique identifier associated with this status representation.
    worker_status_id: typing.Optional[str] = Field(None, alias='workerStatusId')

    # The workers current status.
    status_type: typing.Optional[Literal["ACTIVE", "INACTIVE", "TERMINATED", "PENDING", "IN_PROGRESS"]] = Field(None, alias='statusType')

    # The detailed reason of the workers current status.
    status_reason: typing.Optional[str] = Field(None, alias='statusReason')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
