# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class TelecomResource(BaseModel):
    # The ID for the workers relationship to contact.
    communication_id: typing.Optional[str] = Field(None, alias='communicationId')

    # The country code. Required for POST contacts.
    dial_country: typing.Optional[str] = Field(None, alias='dialCountry')

    # The area code. Required for POST contacts.
    dial_area: typing.Optional[str] = Field(None, alias='dialArea')

    # The phone number. Required for POST contacts.
    dial_number: typing.Optional[str] = Field(None, alias='dialNumber')

    # Enum: \"PHONE\", \"MOBILE_PHONE\"  Indicates whether or not the number is for a mobile device. Required for POST contacts.
    type: typing.Optional[str] = Field(None, alias='type')

    # Enum: \"PERSONAL\", \"BUSINESS\"  A code classifying a designated use associated with a contact method. For example, whether a telephone or email address is one for work communications or one primarily for personal use. This data field cannot be PATCHED. Required for POST contacts.
    usage_type: typing.Optional[str] = Field(None, alias='usageType')

    # The phone extension.
    extension: typing.Optional[str] = Field(None, alias='extension')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
