# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class WorkerFederalTaxResource(BaseModel):
    # The ID for the federal tax item.
    tax_id: typing.Optional[str] = Field(None, alias='taxId')

    # Filing status.
    filing_status: typing.Optional[Literal["SINGLE_OR_MARRIED_FILING_SEPARATELY", "MARRIED_FILING_JOINTLY", "HEAD_OF_HOUSEHOLD"]] = Field(None, alias='filingStatus')

    # See federal W-4 instructions.
    multiple_jobs: typing.Optional[Literal["true", "false"]] = Field(None, alias='multipleJobs')

    # See federal W-4 instructions.
    dependents_amount: typing.Optional[str] = Field(None, alias='dependentsAmount')

    # See federal W-4 instructions.
    other_income: typing.Optional[str] = Field(None, alias='otherIncome')

    # See federal W-4 instructions.
    deductions_amount: typing.Optional[str] = Field(None, alias='deductionsAmount')

    # Additional tax you want withheld each pay period.
    extra_withholding_amount: typing.Optional[str] = Field(None, alias='extraWithholdingAmount')

    # Should federal taxes be withheld.
    taxes_withheld: typing.Optional[Literal["true = Federal taxes withheld", "false = Federal taxes are NOT withheld. Earnings will be reported to state and federal agencies."]] = Field(None, alias='taxesWithheld')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
