# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class WorkerCustomFieldsResource(BaseModel):
    # The unique identifier that is autogenerated when a custom field is created
    worker_custom_field_id: typing.Optional[str] = Field(None, alias='workerCustomFieldId')

    # client Custom Field Id
    custom_field_id: typing.Optional[str] = Field(None, alias='customFieldId')

    # The type of field the custom field is
    type: typing.Optional[Literal["DROPDOWN", "TEXT", "BOOLEAN", "DATE", "NUMERIC, NUMERIC__0_00_ OR NUMERIC__0_0000_"]] = Field(None, alias='type')

    # The value for BOOLEAN type (true/false)
    boolean_value: typing.Optional[bool] = Field(None, alias='booleanValue')

    # The value for TEXT type (any text, alphanumeric, special characters allowed)
    text_value: typing.Optional[str] = Field(None, alias='textValue')

    # Numeric data type can have three formats namely - whole number, second decimal place and fourth decimal place, example: 12 , 12.34 or 12.3456
    numeric_value: typing.Optional[typing.Union[int, float]] = Field(None, alias='numericValue')

    # The value for DATE type , example : 2012-02-01T05:00:00Z
    date_value: typing.Optional[datetime] = Field(None, alias='dateValue')

    # The unique identifier that is autogenerated when dropdown list is created
    dropdown_id: typing.Optional[str] = Field(None, alias='dropdownId')

    # The value for dropdown list
    dropdown_value: typing.Optional[str] = Field(None, alias='dropdownValue')

    # The name of the custom field. Such as: \"Hobbies\"
    custom_field_name: typing.Optional[str] = Field(None, alias='customFieldName')

    # Where to indicate if the custom field is required on the worker where true = required and false = not required
    required: typing.Optional[bool] = Field(None, alias='required')

    # Where to indicate if the custom field is required on the workers pay stub, where true = required and false = not required.
    check_stub: typing.Optional[bool] = Field(None, alias='checkStub')

    # Where to indicate if the custom field is able to be edited by the employee, where true = required and false = not required.
    employee_editable: typing.Optional[bool] = Field(None, alias='employeeEditable')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
