# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from paychex_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    AUTH_OAUTH_V2_TOKEN = "/auth/oauth/v2/token"
    COMPANIES = "/companies"
    COMPANIES_COMPANY_ID = "/companies/{companyId}"
    COMPANIES_COMPANY_ID_CALCULATIONBASES = "/companies/{companyId}/calculationbases"
    COMPANIES_COMPANY_ID_CHECKS = "/companies/{companyId}/checks"
    COMPANIES_COMPANY_ID_CONTACTTYPES = "/companies/{companyId}/contacttypes"
    COMPANIES_COMPANY_ID_CUSTOMFIELDS = "/companies/{companyId}/customfields"
    COMPANIES_COMPANY_ID_CUSTOMFIELDS_CUSTOM_FIELD_ID = "/companies/{companyId}/customfields/{customFieldId}"
    COMPANIES_COMPANY_ID_CUSTOMFIELDS_CUSTOMFIELDID = "/companies/{companyId}/customfields/{customfieldid}"
    COMPANIES_COMPANY_ID_CUSTOMFIELDSCATEGORIES = "/companies/{companyId}/customfieldscategories"
    COMPANIES_COMPANY_ID_CUSTOMFIELDSCATEGORIES_CATEGORY_ID = "/companies/{companyId}/customfieldscategories/{categoryId}"
    COMPANIES_COMPANY_ID_CUSTOMFIELDSCATEGORIES_CATEGORYID = "/companies/{companyId}/customfieldscategories/{categoryid}"
    COMPANIES_COMPANY_ID_JOBS = "/companies/{companyId}/jobs"
    COMPANIES_COMPANY_ID_JOBS_JOB_ID = "/companies/{companyId}/jobs/{jobId}"
    COMPANIES_COMPANY_ID_JOBSEGMENTS = "/companies/{companyId}/jobsegments"
    COMPANIES_COMPANY_ID_JOBTITLES = "/companies/{companyId}/jobtitles"
    COMPANIES_COMPANY_ID_JOBTITLES_JOB_TITLE_ID = "/companies/{companyId}/jobtitles/{jobTitleId}"
    COMPANIES_COMPANY_ID_LABORASSIGNMENTS = "/companies/{companyId}/laborassignments"
    COMPANIES_COMPANY_ID_LABORASSIGNMENTS_LABOR_ASSIGNMENT_ID = "/companies/{companyId}/laborassignments/{laborAssignmentId}"
    COMPANIES_COMPANY_ID_LOCATIONS = "/companies/{companyId}/locations"
    COMPANIES_COMPANY_ID_LOCATIONS_LOCATION_ID = "/companies/{companyId}/locations/{locationId}"
    COMPANIES_COMPANY_ID_ORGANIZATIONS = "/companies/{companyId}/organizations"
    COMPANIES_COMPANY_ID_ORGANIZATIONS_ORG_ID = "/companies/{companyId}/organizations/{orgId}"
    COMPANIES_COMPANY_ID_PAYCOMPONENTS = "/companies/{companyId}/paycomponents"
    COMPANIES_COMPANY_ID_PAYCOMPONENTS_PAYCOMPONENT_ID = "/companies/{companyId}/paycomponents/{paycomponentId}"
    COMPANIES_COMPANY_ID_PAYFREQUENCIES = "/companies/{companyId}/payfrequencies"
    COMPANIES_COMPANY_ID_PAYPERIODS = "/companies/{companyId}/payperiods"
    COMPANIES_COMPANY_ID_PAYPERIODS_PAYPERIOD_ID = "/companies/{companyId}/payperiods/{payperiodId}"
    COMPANIES_COMPANY_ID_WORKERS = "/companies/{companyId}/workers"
    COMPANIES_COMPANY_ID_WORKERSTATUSES = "/companies/{companyId}/workerstatuses"
    COMPANIES_COMPANY_ID_WORKERSTATUSES_STATUS_ID = "/companies/{companyId}/workerstatuses/{statusId}"
    WORKERS_WORKER_ID = "/workers/{workerId}"
    WORKERS_WORKER_ID_ASSIGNMENTDISTRIBUTIONS = "/workers/{workerId}/assignmentdistributions"
    WORKERS_WORKER_ID_CHECKS = "/workers/{workerId}/checks"
    WORKERS_WORKER_ID_CHECKS_EXTERNAL_CHECK_ID = "/workers/{workerId}/checks/{externalCheckId}"
    WORKERS_WORKER_ID_COMMUNICATIONS = "/workers/{workerId}/communications"
    WORKERS_WORKER_ID_COMMUNICATIONS_COMMUNICATION_ID = "/workers/{workerId}/communications/{communicationId}"
    WORKERS_WORKER_ID_COMPENSATION = "/workers/{workerId}/compensation"
    WORKERS_WORKER_ID_COMPENSATION_PAYRATES = "/workers/{workerId}/compensation/payrates"
    WORKERS_WORKER_ID_COMPENSATION_PAYRATES_RATE_ID = "/workers/{workerId}/compensation/payrates/{rateId}"
    WORKERS_WORKER_ID_COMPENSATION_PAYSTANDARDS = "/workers/{workerId}/compensation/paystandards"
    WORKERS_WORKER_ID_CONTACTS = "/workers/{workerId}/contacts"
    WORKERS_WORKER_ID_CONTACTS_CONTACT_ID = "/workers/{workerId}/contacts/{contactId}"
    WORKERS_WORKER_ID_CUSTOMFIELDS = "/workers/{workerId}/customfields"
    WORKERS_WORKER_ID_CUSTOMFIELDS_WORKER_CUSTOM_FIELD_ID = "/workers/{workerId}/customfields/{workerCustomFieldId}"
    WORKERS_WORKER_ID_DIRECTDEPOSITS = "/workers/{workerId}/directdeposits"
    WORKERS_WORKER_ID_DIRECTDEPOSITS_DIRECT_DEPOSIT_ID = "/workers/{workerId}/directdeposits/{directDepositId}"
    WORKERS_WORKER_ID_FEDERALTAX = "/workers/{workerId}/federaltax"
    WORKERS_WORKER_ID_PAYCOMPONENTS = "/workers/{workerId}/paycomponents"
    WORKERS_WORKER_ID_PAYCOMPONENTS_WORKER_COMPONENT_ID = "/workers/{workerId}/paycomponents/{workerComponentId}"
    WORKERS_WORKER_ID_STATUS = "/workers/{workerId}/status"
    WORKERS_WORKER_ID_TIMEOFF = "/workers/{workerId}/timeoff"
    CHECKS = "/checks"
    CHECKS_CHECK_ID_CHECKCOMPONENTS = "/checks/{checkId}/checkcomponents"
    CHECKS_CHECK_ID_CHECKCOMPONENTS_CHECK_COMPONENT_ID = "/checks/{checkId}/checkcomponents/{checkComponentId}"
    MANAGEMENT_DOMAINS = "/management/domains"
    MANAGEMENT_HOOKS = "/management/hooks"
    MANAGEMENT_HOOKS_HOOK_ID = "/management/hooks/{hookId}"
    MANAGEMENT_REQUESTCLIENTACCESS = "/management/requestclientaccess"
