# coding: utf-8
"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from paychex_python_sdk.client_custom import ClientCustom
from paychex_python_sdk.configuration import Configuration
from paychex_python_sdk.api_client import ApiClient
from paychex_python_sdk.type_util import copy_signature
from paychex_python_sdk.apis.tags.authentication_api import AuthenticationApi
from paychex_python_sdk.apis.tags.company_api import CompanyApi
from paychex_python_sdk.apis.tags.management_api import ManagementApi
from paychex_python_sdk.apis.tags.payroll_api import PayrollApi
from paychex_python_sdk.apis.tags.webhooks_api import WebhooksApi
from paychex_python_sdk.apis.tags.worker_api import WorkerApi



class Paychex(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.authentication: AuthenticationApi = AuthenticationApi(api_client)
        self.company: CompanyApi = CompanyApi(api_client)
        self.management: ManagementApi = ManagementApi(api_client)
        self.payroll: PayrollApi = PayrollApi(api_client)
        self.webhooks: WebhooksApi = WebhooksApi(api_client)
        self.worker: WorkerApi = WorkerApi(api_client)
