# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from paychex_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from paychex_python_sdk.api_response import AsyncGeneratorResponse
from paychex_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paychex_python_sdk import schemas  # noqa: F401

from paychex_python_sdk.model.legal_id_resource import LegalIdResource as LegalIdResourceSchema
from paychex_python_sdk.model.worker_resource import WorkerResource as WorkerResourceSchema
from paychex_python_sdk.model.status import Status as StatusSchema
from paychex_python_sdk.model.organization_resource import OrganizationResource as OrganizationResourceSchema
from paychex_python_sdk.model.name_resource import NameResource as NameResourceSchema
from paychex_python_sdk.model.job_title_resource import JobTitleResource as JobTitleResourceSchema
from paychex_python_sdk.model.error_resource import ErrorResource as ErrorResourceSchema
from paychex_python_sdk.model.supervisor_resource import SupervisorResource as SupervisorResourceSchema
from paychex_python_sdk.model.communication_resource import CommunicationResource as CommunicationResourceSchema

from paychex_python_sdk.type.communication_resource import CommunicationResource
from paychex_python_sdk.type.supervisor_resource import SupervisorResource
from paychex_python_sdk.type.legal_id_resource import LegalIdResource
from paychex_python_sdk.type.status import Status
from paychex_python_sdk.type.job_title_resource import JobTitleResource
from paychex_python_sdk.type.worker_resource import WorkerResource
from paychex_python_sdk.type.name_resource import NameResource
from paychex_python_sdk.type.organization_resource import OrganizationResource
from paychex_python_sdk.type.error_resource import ErrorResource

from ...api_client import Dictionary
from paychex_python_sdk.pydantic.organization_resource import OrganizationResource as OrganizationResourcePydantic
from paychex_python_sdk.pydantic.legal_id_resource import LegalIdResource as LegalIdResourcePydantic
from paychex_python_sdk.pydantic.communication_resource import CommunicationResource as CommunicationResourcePydantic
from paychex_python_sdk.pydantic.status import Status as StatusPydantic
from paychex_python_sdk.pydantic.error_resource import ErrorResource as ErrorResourcePydantic
from paychex_python_sdk.pydantic.worker_resource import WorkerResource as WorkerResourcePydantic
from paychex_python_sdk.pydantic.supervisor_resource import SupervisorResource as SupervisorResourcePydantic
from paychex_python_sdk.pydantic.name_resource import NameResource as NameResourcePydantic
from paychex_python_sdk.pydantic.job_title_resource import JobTitleResource as JobTitleResourcePydantic

# Path params
CompanyIdSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'companyId': typing.Union[CompanyIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_company_id = api_client.PathParameter(
    name="companyId",
    style=api_client.ParameterStyle.SIMPLE,
    schema=CompanyIdSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationVndPaychexWorkersV1json = WorkerResourceSchema


request_body_worker_resource = api_client.RequestBody(
    content={
        'application/vnd.paychex.workers.v1+json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationVndPaychexWorkersV1json),
    },
    required=True,
)
SchemaFor201ResponseBodyApplicationJson = WorkerResourceSchema
SchemaFor201ResponseBodyApplicationVndPaychexWorkersV1json = WorkerResourceSchema


@dataclass
class ApiResponseFor201(api_client.ApiResponse):
    body: WorkerResource


@dataclass
class ApiResponseFor201Async(api_client.AsyncApiResponse):
    body: WorkerResource


_response_for_201 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor201,
    response_cls_async=ApiResponseFor201Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor201ResponseBodyApplicationJson),
        'application/vnd.paychex.workers.v1+json': api_client.MediaType(
            schema=SchemaFor201ResponseBodyApplicationVndPaychexWorkersV1json),
    },
)
SchemaFor400ResponseBodyApplicationJson = ErrorResourceSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: ErrorResource


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: ErrorResource


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor401ResponseBodyApplicationJson = ErrorResourceSchema


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: ErrorResource


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: ErrorResource


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationJson),
    },
)
SchemaFor403ResponseBodyApplicationJson = ErrorResourceSchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: ErrorResource


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: ErrorResource


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
    },
)
SchemaFor405ResponseBodyApplicationJson = ErrorResourceSchema


@dataclass
class ApiResponseFor405(api_client.ApiResponse):
    body: ErrorResource


@dataclass
class ApiResponseFor405Async(api_client.AsyncApiResponse):
    body: ErrorResource


_response_for_405 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor405,
    response_cls_async=ApiResponseFor405Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor405ResponseBodyApplicationJson),
    },
)
SchemaFor406ResponseBodyApplicationJson = ErrorResourceSchema


@dataclass
class ApiResponseFor406(api_client.ApiResponse):
    body: ErrorResource


@dataclass
class ApiResponseFor406Async(api_client.AsyncApiResponse):
    body: ErrorResource


_response_for_406 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor406,
    response_cls_async=ApiResponseFor406Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor406ResponseBodyApplicationJson),
    },
)
SchemaFor500ResponseBodyApplicationJson = ErrorResourceSchema


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: ErrorResource


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: ErrorResource


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
    'application/vnd.paychex.workers.v1+json',
)


class BaseApi(api_client.Api):

    def _add_in_progress_workers_mapped_args(
        self,
        company_id: str,
        worker_id: typing.Optional[str] = None,
        employee_id: typing.Optional[str] = None,
        worker_type: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        exemption_type: typing.Optional[str] = None,
        birth_date: typing.Optional[datetime] = None,
        sex: typing.Optional[str] = None,
        ethnicity_code: typing.Optional[str] = None,
        hire_date: typing.Optional[datetime] = None,
        clock_id: typing.Optional[str] = None,
        name: typing.Optional[NameResource] = None,
        legal_id: typing.Optional[LegalIdResource] = None,
        labor_assignment_id: typing.Optional[str] = None,
        job_id: typing.Optional[str] = None,
        location_id: typing.Optional[str] = None,
        job: typing.Optional[JobTitleResource] = None,
        organization: typing.Optional[OrganizationResource] = None,
        supervisor: typing.Optional[SupervisorResource] = None,
        current_status: typing.Optional[Status] = None,
        communications: typing.Optional[typing.List[CommunicationResource]] = None,
        worker_correlation_id: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        _body = {}
        if worker_id is not None:
            _body["workerId"] = worker_id
        if employee_id is not None:
            _body["employeeId"] = employee_id
        if worker_type is not None:
            _body["workerType"] = worker_type
        if employment_type is not None:
            _body["employmentType"] = employment_type
        if exemption_type is not None:
            _body["exemptionType"] = exemption_type
        if birth_date is not None:
            _body["birthDate"] = birth_date
        if sex is not None:
            _body["sex"] = sex
        if ethnicity_code is not None:
            _body["ethnicityCode"] = ethnicity_code
        if hire_date is not None:
            _body["hireDate"] = hire_date
        if clock_id is not None:
            _body["clockId"] = clock_id
        if name is not None:
            _body["name"] = name
        if legal_id is not None:
            _body["legalId"] = legal_id
        if labor_assignment_id is not None:
            _body["laborAssignmentId"] = labor_assignment_id
        if job_id is not None:
            _body["jobId"] = job_id
        if location_id is not None:
            _body["locationId"] = location_id
        if job is not None:
            _body["job"] = job
        if organization is not None:
            _body["organization"] = organization
        if supervisor is not None:
            _body["supervisor"] = supervisor
        if current_status is not None:
            _body["currentStatus"] = current_status
        if communications is not None:
            _body["communications"] = communications
        if worker_correlation_id is not None:
            _body["workerCorrelationId"] = worker_correlation_id
        args.body = _body
        if company_id is not None:
            _path_params["companyId"] = company_id
        args.path = _path_params
        return args

    async def _aadd_in_progress_workers_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/vnd.paychex.workers.v1+json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        In Progress Workers
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_company_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/companies/{companyId}/workers',
            body=body,
            headers=_headers,
        )
        serialized_data = request_body_worker_resource.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _add_in_progress_workers_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/vnd.paychex.workers.v1+json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        In Progress Workers
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_company_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/companies/{companyId}/workers',
            body=body,
            headers=_headers,
        )
        serialized_data = request_body_worker_resource.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class AddInProgressWorkersRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aadd_in_progress_workers(
        self,
        company_id: str,
        worker_id: typing.Optional[str] = None,
        employee_id: typing.Optional[str] = None,
        worker_type: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        exemption_type: typing.Optional[str] = None,
        birth_date: typing.Optional[datetime] = None,
        sex: typing.Optional[str] = None,
        ethnicity_code: typing.Optional[str] = None,
        hire_date: typing.Optional[datetime] = None,
        clock_id: typing.Optional[str] = None,
        name: typing.Optional[NameResource] = None,
        legal_id: typing.Optional[LegalIdResource] = None,
        labor_assignment_id: typing.Optional[str] = None,
        job_id: typing.Optional[str] = None,
        location_id: typing.Optional[str] = None,
        job: typing.Optional[JobTitleResource] = None,
        organization: typing.Optional[OrganizationResource] = None,
        supervisor: typing.Optional[SupervisorResource] = None,
        current_status: typing.Optional[Status] = None,
        communications: typing.Optional[typing.List[CommunicationResource]] = None,
        worker_correlation_id: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._add_in_progress_workers_mapped_args(
            company_id=company_id,
            worker_id=worker_id,
            employee_id=employee_id,
            worker_type=worker_type,
            employment_type=employment_type,
            exemption_type=exemption_type,
            birth_date=birth_date,
            sex=sex,
            ethnicity_code=ethnicity_code,
            hire_date=hire_date,
            clock_id=clock_id,
            name=name,
            legal_id=legal_id,
            labor_assignment_id=labor_assignment_id,
            job_id=job_id,
            location_id=location_id,
            job=job,
            organization=organization,
            supervisor=supervisor,
            current_status=current_status,
            communications=communications,
            worker_correlation_id=worker_correlation_id,
        )
        return await self._aadd_in_progress_workers_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def add_in_progress_workers(
        self,
        company_id: str,
        worker_id: typing.Optional[str] = None,
        employee_id: typing.Optional[str] = None,
        worker_type: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        exemption_type: typing.Optional[str] = None,
        birth_date: typing.Optional[datetime] = None,
        sex: typing.Optional[str] = None,
        ethnicity_code: typing.Optional[str] = None,
        hire_date: typing.Optional[datetime] = None,
        clock_id: typing.Optional[str] = None,
        name: typing.Optional[NameResource] = None,
        legal_id: typing.Optional[LegalIdResource] = None,
        labor_assignment_id: typing.Optional[str] = None,
        job_id: typing.Optional[str] = None,
        location_id: typing.Optional[str] = None,
        job: typing.Optional[JobTitleResource] = None,
        organization: typing.Optional[OrganizationResource] = None,
        supervisor: typing.Optional[SupervisorResource] = None,
        current_status: typing.Optional[Status] = None,
        communications: typing.Optional[typing.List[CommunicationResource]] = None,
        worker_correlation_id: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._add_in_progress_workers_mapped_args(
            company_id=company_id,
            worker_id=worker_id,
            employee_id=employee_id,
            worker_type=worker_type,
            employment_type=employment_type,
            exemption_type=exemption_type,
            birth_date=birth_date,
            sex=sex,
            ethnicity_code=ethnicity_code,
            hire_date=hire_date,
            clock_id=clock_id,
            name=name,
            legal_id=legal_id,
            labor_assignment_id=labor_assignment_id,
            job_id=job_id,
            location_id=location_id,
            job=job,
            organization=organization,
            supervisor=supervisor,
            current_status=current_status,
            communications=communications,
            worker_correlation_id=worker_correlation_id,
        )
        return self._add_in_progress_workers_oapg(
            body=args.body,
            path_params=args.path,
        )

class AddInProgressWorkers(BaseApi):

    async def aadd_in_progress_workers(
        self,
        company_id: str,
        worker_id: typing.Optional[str] = None,
        employee_id: typing.Optional[str] = None,
        worker_type: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        exemption_type: typing.Optional[str] = None,
        birth_date: typing.Optional[datetime] = None,
        sex: typing.Optional[str] = None,
        ethnicity_code: typing.Optional[str] = None,
        hire_date: typing.Optional[datetime] = None,
        clock_id: typing.Optional[str] = None,
        name: typing.Optional[NameResource] = None,
        legal_id: typing.Optional[LegalIdResource] = None,
        labor_assignment_id: typing.Optional[str] = None,
        job_id: typing.Optional[str] = None,
        location_id: typing.Optional[str] = None,
        job: typing.Optional[JobTitleResource] = None,
        organization: typing.Optional[OrganizationResource] = None,
        supervisor: typing.Optional[SupervisorResource] = None,
        current_status: typing.Optional[Status] = None,
        communications: typing.Optional[typing.List[CommunicationResource]] = None,
        worker_correlation_id: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> WorkerResourcePydantic:
        raw_response = await self.raw.aadd_in_progress_workers(
            company_id=company_id,
            worker_id=worker_id,
            employee_id=employee_id,
            worker_type=worker_type,
            employment_type=employment_type,
            exemption_type=exemption_type,
            birth_date=birth_date,
            sex=sex,
            ethnicity_code=ethnicity_code,
            hire_date=hire_date,
            clock_id=clock_id,
            name=name,
            legal_id=legal_id,
            labor_assignment_id=labor_assignment_id,
            job_id=job_id,
            location_id=location_id,
            job=job,
            organization=organization,
            supervisor=supervisor,
            current_status=current_status,
            communications=communications,
            worker_correlation_id=worker_correlation_id,
            **kwargs,
        )
        if validate:
            return WorkerResourcePydantic(**raw_response.body)
        return api_client.construct_model_instance(WorkerResourcePydantic, raw_response.body)
    
    
    def add_in_progress_workers(
        self,
        company_id: str,
        worker_id: typing.Optional[str] = None,
        employee_id: typing.Optional[str] = None,
        worker_type: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        exemption_type: typing.Optional[str] = None,
        birth_date: typing.Optional[datetime] = None,
        sex: typing.Optional[str] = None,
        ethnicity_code: typing.Optional[str] = None,
        hire_date: typing.Optional[datetime] = None,
        clock_id: typing.Optional[str] = None,
        name: typing.Optional[NameResource] = None,
        legal_id: typing.Optional[LegalIdResource] = None,
        labor_assignment_id: typing.Optional[str] = None,
        job_id: typing.Optional[str] = None,
        location_id: typing.Optional[str] = None,
        job: typing.Optional[JobTitleResource] = None,
        organization: typing.Optional[OrganizationResource] = None,
        supervisor: typing.Optional[SupervisorResource] = None,
        current_status: typing.Optional[Status] = None,
        communications: typing.Optional[typing.List[CommunicationResource]] = None,
        worker_correlation_id: typing.Optional[str] = None,
        validate: bool = False,
    ) -> WorkerResourcePydantic:
        raw_response = self.raw.add_in_progress_workers(
            company_id=company_id,
            worker_id=worker_id,
            employee_id=employee_id,
            worker_type=worker_type,
            employment_type=employment_type,
            exemption_type=exemption_type,
            birth_date=birth_date,
            sex=sex,
            ethnicity_code=ethnicity_code,
            hire_date=hire_date,
            clock_id=clock_id,
            name=name,
            legal_id=legal_id,
            labor_assignment_id=labor_assignment_id,
            job_id=job_id,
            location_id=location_id,
            job=job,
            organization=organization,
            supervisor=supervisor,
            current_status=current_status,
            communications=communications,
            worker_correlation_id=worker_correlation_id,
        )
        if validate:
            return WorkerResourcePydantic(**raw_response.body)
        return api_client.construct_model_instance(WorkerResourcePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        company_id: str,
        worker_id: typing.Optional[str] = None,
        employee_id: typing.Optional[str] = None,
        worker_type: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        exemption_type: typing.Optional[str] = None,
        birth_date: typing.Optional[datetime] = None,
        sex: typing.Optional[str] = None,
        ethnicity_code: typing.Optional[str] = None,
        hire_date: typing.Optional[datetime] = None,
        clock_id: typing.Optional[str] = None,
        name: typing.Optional[NameResource] = None,
        legal_id: typing.Optional[LegalIdResource] = None,
        labor_assignment_id: typing.Optional[str] = None,
        job_id: typing.Optional[str] = None,
        location_id: typing.Optional[str] = None,
        job: typing.Optional[JobTitleResource] = None,
        organization: typing.Optional[OrganizationResource] = None,
        supervisor: typing.Optional[SupervisorResource] = None,
        current_status: typing.Optional[Status] = None,
        communications: typing.Optional[typing.List[CommunicationResource]] = None,
        worker_correlation_id: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._add_in_progress_workers_mapped_args(
            company_id=company_id,
            worker_id=worker_id,
            employee_id=employee_id,
            worker_type=worker_type,
            employment_type=employment_type,
            exemption_type=exemption_type,
            birth_date=birth_date,
            sex=sex,
            ethnicity_code=ethnicity_code,
            hire_date=hire_date,
            clock_id=clock_id,
            name=name,
            legal_id=legal_id,
            labor_assignment_id=labor_assignment_id,
            job_id=job_id,
            location_id=location_id,
            job=job,
            organization=organization,
            supervisor=supervisor,
            current_status=current_status,
            communications=communications,
            worker_correlation_id=worker_correlation_id,
        )
        return await self._aadd_in_progress_workers_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def post(
        self,
        company_id: str,
        worker_id: typing.Optional[str] = None,
        employee_id: typing.Optional[str] = None,
        worker_type: typing.Optional[str] = None,
        employment_type: typing.Optional[str] = None,
        exemption_type: typing.Optional[str] = None,
        birth_date: typing.Optional[datetime] = None,
        sex: typing.Optional[str] = None,
        ethnicity_code: typing.Optional[str] = None,
        hire_date: typing.Optional[datetime] = None,
        clock_id: typing.Optional[str] = None,
        name: typing.Optional[NameResource] = None,
        legal_id: typing.Optional[LegalIdResource] = None,
        labor_assignment_id: typing.Optional[str] = None,
        job_id: typing.Optional[str] = None,
        location_id: typing.Optional[str] = None,
        job: typing.Optional[JobTitleResource] = None,
        organization: typing.Optional[OrganizationResource] = None,
        supervisor: typing.Optional[SupervisorResource] = None,
        current_status: typing.Optional[Status] = None,
        communications: typing.Optional[typing.List[CommunicationResource]] = None,
        worker_correlation_id: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._add_in_progress_workers_mapped_args(
            company_id=company_id,
            worker_id=worker_id,
            employee_id=employee_id,
            worker_type=worker_type,
            employment_type=employment_type,
            exemption_type=exemption_type,
            birth_date=birth_date,
            sex=sex,
            ethnicity_code=ethnicity_code,
            hire_date=hire_date,
            clock_id=clock_id,
            name=name,
            legal_id=legal_id,
            labor_assignment_id=labor_assignment_id,
            job_id=job_id,
            location_id=location_id,
            job=job,
            organization=organization,
            supervisor=supervisor,
            current_status=current_status,
            communications=communications,
            worker_correlation_id=worker_correlation_id,
        )
        return self._add_in_progress_workers_oapg(
            body=args.body,
            path_params=args.path,
        )

