# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paychex_python_sdk import schemas  # noqa: F401


class ClientPayComponentOptions(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            optValueId = schemas.Int64Schema
            optValueName = schemas.StrSchema
            optValueTypeId = schemas.Int64Schema
            optValue = schemas.StrSchema
            __annotations__ = {
                "optValueId": optValueId,
                "optValueName": optValueName,
                "optValueTypeId": optValueTypeId,
                "optValue": optValue,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["optValueId"]) -> MetaOapg.properties.optValueId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["optValueName"]) -> MetaOapg.properties.optValueName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["optValueTypeId"]) -> MetaOapg.properties.optValueTypeId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["optValue"]) -> MetaOapg.properties.optValue: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["optValueId", "optValueName", "optValueTypeId", "optValue", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["optValueId"]) -> typing.Union[MetaOapg.properties.optValueId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["optValueName"]) -> typing.Union[MetaOapg.properties.optValueName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["optValueTypeId"]) -> typing.Union[MetaOapg.properties.optValueTypeId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["optValue"]) -> typing.Union[MetaOapg.properties.optValue, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["optValueId", "optValueName", "optValueTypeId", "optValue", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        optValueId: typing.Union[MetaOapg.properties.optValueId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        optValueName: typing.Union[MetaOapg.properties.optValueName, str, schemas.Unset] = schemas.unset,
        optValueTypeId: typing.Union[MetaOapg.properties.optValueTypeId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        optValue: typing.Union[MetaOapg.properties.optValue, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ClientPayComponentOptions':
        return super().__new__(
            cls,
            *args,
            optValueId=optValueId,
            optValueName=optValueName,
            optValueTypeId=optValueTypeId,
            optValue=optValue,
            _configuration=_configuration,
            **kwargs,
        )
