# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paychex_python_sdk import schemas  # noqa: F401


class ContactTypeResource1(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The type of this worker contact. Required for POST contacts.
    """


    class MetaOapg:
        
        class properties:
            contactTypeId = schemas.StrSchema
            contactTypeName = schemas.StrSchema
            __annotations__ = {
                "contactTypeId": contactTypeId,
                "contactTypeName": contactTypeName,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contactTypeId"]) -> MetaOapg.properties.contactTypeId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contactTypeName"]) -> MetaOapg.properties.contactTypeName: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["contactTypeId", "contactTypeName", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contactTypeId"]) -> typing.Union[MetaOapg.properties.contactTypeId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contactTypeName"]) -> typing.Union[MetaOapg.properties.contactTypeName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["contactTypeId", "contactTypeName", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        contactTypeId: typing.Union[MetaOapg.properties.contactTypeId, str, schemas.Unset] = schemas.unset,
        contactTypeName: typing.Union[MetaOapg.properties.contactTypeName, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ContactTypeResource1':
        return super().__new__(
            cls,
            *args,
            contactTypeId=contactTypeId,
            contactTypeName=contactTypeName,
            _configuration=_configuration,
            **kwargs,
        )
