# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paychex_python_sdk import schemas  # noqa: F401


class EntityResource(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The organization associated with this relationship. The relationship must have either a person or entity.
    """


    class MetaOapg:
        
        class properties:
            entityId = schemas.StrSchema
            entityName = schemas.StrSchema
        
            @staticmethod
            def communication() -> typing.Type['EntityCommunicationResource']:
                return EntityCommunicationResource
            __annotations__ = {
                "entityId": entityId,
                "entityName": entityName,
                "communication": communication,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["entityId"]) -> MetaOapg.properties.entityId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["entityName"]) -> MetaOapg.properties.entityName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["communication"]) -> 'EntityCommunicationResource': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["entityId", "entityName", "communication", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["entityId"]) -> typing.Union[MetaOapg.properties.entityId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["entityName"]) -> typing.Union[MetaOapg.properties.entityName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["communication"]) -> typing.Union['EntityCommunicationResource', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["entityId", "entityName", "communication", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        entityId: typing.Union[MetaOapg.properties.entityId, str, schemas.Unset] = schemas.unset,
        entityName: typing.Union[MetaOapg.properties.entityName, str, schemas.Unset] = schemas.unset,
        communication: typing.Union['EntityCommunicationResource', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EntityResource':
        return super().__new__(
            cls,
            *args,
            entityId=entityId,
            entityName=entityName,
            communication=communication,
            _configuration=_configuration,
            **kwargs,
        )

from paychex_python_sdk.model.entity_communication_resource import EntityCommunicationResource
