# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paychex_python_sdk import schemas  # noqa: F401


class JobSegmentsResource(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Data elements of a Job Number to show the segments and number.For segmentation this can be up to 3 different segments.
    """


    class MetaOapg:
        
        class properties:
            segment1 = schemas.StrSchema
            segment2 = schemas.StrSchema
            segment3 = schemas.StrSchema
            __annotations__ = {
                "segment1": segment1,
                "segment2": segment2,
                "segment3": segment3,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["segment1"]) -> MetaOapg.properties.segment1: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["segment2"]) -> MetaOapg.properties.segment2: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["segment3"]) -> MetaOapg.properties.segment3: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["segment1", "segment2", "segment3", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["segment1"]) -> typing.Union[MetaOapg.properties.segment1, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["segment2"]) -> typing.Union[MetaOapg.properties.segment2, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["segment3"]) -> typing.Union[MetaOapg.properties.segment3, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["segment1", "segment2", "segment3", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        segment1: typing.Union[MetaOapg.properties.segment1, str, schemas.Unset] = schemas.unset,
        segment2: typing.Union[MetaOapg.properties.segment2, str, schemas.Unset] = schemas.unset,
        segment3: typing.Union[MetaOapg.properties.segment3, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'JobSegmentsResource':
        return super().__new__(
            cls,
            *args,
            segment1=segment1,
            segment2=segment2,
            segment3=segment3,
            _configuration=_configuration,
            **kwargs,
        )
