# coding: utf-8

"""
    External API

      # Developer Resources  Refer [Developer Resources](https://developer.paychex.com/resources/overview/) for more details on API specification 

    The version of the OpenAPI document: 1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from paychex_python_sdk import schemas  # noqa: F401


class MetadataResource(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            contentItemCount = schemas.Int32Schema
        
            @staticmethod
            def pagination() -> typing.Type['PaginationMetadataResource']:
                return PaginationMetadataResource
            __annotations__ = {
                "contentItemCount": contentItemCount,
                "pagination": pagination,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contentItemCount"]) -> MetaOapg.properties.contentItemCount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pagination"]) -> 'PaginationMetadataResource': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["contentItemCount", "pagination", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contentItemCount"]) -> typing.Union[MetaOapg.properties.contentItemCount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pagination"]) -> typing.Union['PaginationMetadataResource', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["contentItemCount", "pagination", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        contentItemCount: typing.Union[MetaOapg.properties.contentItemCount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        pagination: typing.Union['PaginationMetadataResource', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MetadataResource':
        return super().__new__(
            cls,
            *args,
            contentItemCount=contentItemCount,
            pagination=pagination,
            _configuration=_configuration,
            **kwargs,
        )

from paychex_python_sdk.model.pagination_metadata_resource import PaginationMetadataResource
